export const COMPANY_TYPES = [
    { ticker: 'NEXUS', sector: 'TECH', archetype: 'stable' },
    { ticker: 'QCI', sector: 'TECH', archetype: 'risky' },
    { ticker: 'CLSE', sector: 'TECH', archetype: 'moderate' },
    { ticker: 'NSMC', sector: 'TECH', archetype: 'cyclical' },

    { ticker: 'AGB', sector: 'FINANCE', archetype: 'stable' },
    { ticker: 'CRC', sector: 'FINANCE', archetype: 'risky' },
    { ticker: 'SGI', sector: 'FINANCE', archetype: 'moderate' },
    { ticker: 'FINT', sector: 'FINANCE', archetype: 'risky' },

    { ticker: 'MEGA', sector: 'RETAIL', archetype: 'stable' },
    { ticker: 'TREND', sector: 'RETAIL', archetype: 'risky' },
    { ticker: 'GLG', sector: 'RETAIL', archetype: 'moderate' },
    { ticker: 'CLICK', sector: 'RETAIL', archetype: 'risky' },

    { ticker: 'IDYN', sector: 'MANUFACTURING', archetype: 'stable' },
    { ticker: 'AUTO', sector: 'MANUFACTURING', archetype: 'cyclical' },
    { ticker: 'AERO', sector: 'MANUFACTURING', archetype: 'stable' },
    { ticker: 'GSYS', sector: 'MANUFACTURING', archetype: 'risky' },

    { ticker: 'GMED', sector: 'PHARMA', archetype: 'defensive' },
    { ticker: 'BIOV', sector: 'PHARMA', archetype: 'risky' },
    { ticker: 'GENH', sector: 'PHARMA', archetype: 'stable' },
    { ticker: 'NEURO', sector: 'PHARMA', archetype: 'risky' },
];

export const SECTOR_LABELS = {
    TECH: 'Technology',
    FINANCE: 'Finance',
    RETAIL: 'Retail',
    MANUFACTURING: 'Manufacturing',
    PHARMA: 'Pharma',
};

export const HEADLINE_TEMPLATES = [
    {
        id: 0,
        scope: 'ticker',
        sectors: ['TECH'],
        sentimentRange: [6, 10],
        text: '{ticker} beats earnings expectations',
    },
    {
        id: 1,
        scope: 'ticker',
        sectors: ['TECH'],
        sentimentRange: [-9, -5],
        text: '{ticker} faces fresh antitrust investigation',
    },
    {
        id: 2,
        scope: 'ticker',
        sectors: ['TECH'],
        sentimentRange: [-6, -3],
        text: 'Major security breach affects millions of {ticker} customers',
    },
    {
        id: 3,
        scope: 'ticker',
        sectors: ['TECH'],
        sentimentRange: [-8, -4],
        text: '{ticker} warns of semiconductor oversupply and expected price cuts',
    },
    {
        id: 4,
        scope: 'sector',
        sectors: ['FINANCE'],
        sentimentRange: [4, 8],
        text: 'Rate-cut expectations lift {sector} lending outlook',
    },
    {
        id: 5,
        scope: 'ticker',
        sectors: ['FINANCE'],
        sentimentRange: [-8, -4],
        text: '{ticker} raises loan-loss provisions after weaker credit trends',
    },
    {
        id: 6,
        scope: 'ticker',
        sectors: ['RETAIL'],
        sentimentRange: [4, 8],
        text: '{ticker} posts sales above analyst estimates',
    },
    {
        id: 7,
        scope: 'ticker',
        sectors: ['RETAIL'],
        sentimentRange: [-9, -5],
        text: '{ticker} flags rising inventory and deeper markdown risk',
    },
    {
        id: 8,
        scope: 'ticker',
        sectors: ['MANUFACTURING'],
        sentimentRange: [5, 9],
        text: '{ticker} awarded major long-term defense contract',
    },
    {
        id: 9,
        scope: 'sector',
        sectors: ['MANUFACTURING'],
        sentimentRange: [-8, -3],
        text: 'President enacts tariffs: {sector} costs expected to rise',
    },
    {
        id: 10,
        scope: 'ticker',
        sectors: ['PHARMA'],
        sentimentRange: [8, 10],
        text: '{ticker} secures FDA approval for new drug',
    },
    {
        id: 11,
        scope: 'ticker',
        sectors: ['PHARMA'],
        sentimentRange: [-10, -7],
        text: '{ticker} says late-stage clinical trial was unsuccessful',
    },
    {
        id: 12,
        scope: 'global',
        sentimentRange: [2, 6],
        text: 'Risk tolerance improves after interest rates lowered',
    },
    {
        id: 13,
        scope: 'global',
        sentimentRange: [-6, -2],
        text: 'Markets turn defensive as ceasefire negotiations stall',
    },
    {
        id: 14,
        scope: 'sector',
        sectors: ['TECH', 'MANUFACTURING'],
        sentimentRange: [3, 6],
        text: 'Large deposits of rare earth minerals discovered in Nevada'
    },
    {
        id: 15,
        scope: 'global',
        sentimentRange: [2, 5],
        text: 'Federal stimulus package approved to support households and small businesses',
        isStimulus: true,
        stimulusCashAmount: 5000,
    },
    {
        id: 16,
        scope: 'sector',
        sectors: ['TECH'],
        sentimentRange: [4, 8],
        text: 'Corporate software spending rises, lifting the {sector} outlook',
    },
    {
        id: 17,
        scope: 'sector',
        sectors: ['TECH'],
        sentimentRange: [-8, -4],
        text: 'New data privacy rules raise compliance costs for {sector} companies',
    },
    {
        id: 18,
        scope: 'ticker',
        sectors: ['TECH'],
        sentimentRange: [5, 9],
        text: '{ticker} announces a major cloud services contract',
    },
    {
        id: 19,
        scope: 'ticker',
        sectors: ['TECH'],
        sentimentRange: [-9, -5],
        text: '{ticker} delays a key product launch after quality concerns',
    },
    {
        id: 20,
        scope: 'ticker',
        sectors: ['TECH'],
        sentimentRange: [3, 6],
        text: '{ticker} reports stronger demand for artificial intelligence tools',
    },
    {
        id: 21,
        scope: 'ticker',
        sectors: ['TECH'],
        sentimentRange: [-6, -3],
        // Competing platform implies some other company in the sector should increase in price
        // so maybe i'll need to add "sideEffect" attribute with a ticker name or sector name
        // in order to apply the inverse of this sentiment to that other ticker/sector sentiment value
        // also do i even have sentiment for sectors? i think just sentiment for each ticker in that sector
        // which works just as well i suppose
        text: '{ticker} loses a large customer to a competing platform',
    },
    {
        id: 22,
        scope: 'sector',
        sectors: ['FINANCE'],
        sentimentRange: [4, 8],
        text: 'Loan demand improves across the {sector} sector',
    },
    {
        id: 23,
        scope: 'sector',
        sectors: ['FINANCE'],
        sentimentRange: [-8, -4],
        text: 'Rising defaults pressure the {sector} sector',
    },
    {
        id: 24,
        scope: 'ticker',
        sectors: ['FINANCE'],
        sentimentRange: [5, 9],
        text: '{ticker} raises its profit forecast after stronger trading revenue',
    },
    {
        id: 25,
        scope: 'ticker',
        sectors: ['FINANCE'],
        sentimentRange: [-9, -5],
        text: '{ticker} discloses losses tied to risky loans',
    },
    {
        id: 26,
        scope: 'ticker',
        sectors: ['FINANCE'],
        sentimentRange: [3, 6],
        text: '{ticker} signs a new payments partnership with a major retailer',
    },
    {
        id: 27,
        scope: 'ticker',
        sectors: ['FINANCE'],
        sentimentRange: [-6, -3],
        text: '{ticker} faces a regulatory review over customer fees',
    },
    {
        id: 28,
        scope: 'sector',
        sectors: ['RETAIL'],
        sentimentRange: [4, 8],
        text: 'Consumer spending improves, helping the {sector} sector',
    },
    {
        id: 29,
        scope: 'sector',
        sectors: ['RETAIL'],
        sentimentRange: [-8, -4],
        text: 'Weak store traffic weighs on the {sector} sector',
    },
    {
        id: 30,
        scope: 'ticker',
        sectors: ['RETAIL'],
        sentimentRange: [5, 9],
        text: '{ticker} reports strong holiday sales and higher profit margins',
    },
    {
        id: 31,
        scope: 'ticker',
        sectors: ['RETAIL'],
        sentimentRange: [-9, -5],
        text: '{ticker} cuts its outlook after slower online sales',
    },
    {
        id: 32,
        scope: 'ticker',
        sectors: ['RETAIL'],
        sentimentRange: [3, 6],
        text: '{ticker} expands same-day delivery to more cities',
    },
    {
        id: 33,
        scope: 'ticker',
        sectors: ['RETAIL'],
        sentimentRange: [-6, -3],
        text: '{ticker} warns that shipping costs are rising faster than expected',
    },
    {
        id: 34,
        scope: 'sector',
        sectors: ['MANUFACTURING'],
        sentimentRange: [4, 8],
        text: 'Factory orders rise across the {sector} sector',
    },
    {
        id: 35,
        scope: 'sector',
        sectors: ['MANUFACTURING'],
        sentimentRange: [-8, -4],
        text: 'Supplier delays slow production across the {sector} sector',
    },
    {
        id: 36,
        scope: 'ticker',
        sectors: ['MANUFACTURING'],
        sentimentRange: [5, 9],
        text: '{ticker} wins a long-term supply deal with a major customer',
    },
    {
        id: 37,
        scope: 'ticker',
        sectors: ['MANUFACTURING'],
        sentimentRange: [-9, -5],
        text: '{ticker} shuts down a plant temporarily after equipment problems',
    },
    {
        id: 38,
        scope: 'ticker',
        sectors: ['MANUFACTURING'],
        sentimentRange: [3, 6],
        text: '{ticker} improves production efficiency with new automation',
    },
    {
        id: 39,
        scope: 'ticker',
        sectors: ['MANUFACTURING'],
        sentimentRange: [-6, -3],
        text: '{ticker} warns that raw material costs are squeezing margins',
    },
    {
        id: 40,
        scope: 'sector',
        sectors: ['PHARMA'],
        sentimentRange: [4, 8],
        text: 'Healthcare demand supports a stronger {sector} outlook',
    },
    {
        id: 41,
        scope: 'sector',
        sectors: ['PHARMA'],
        sentimentRange: [-8, -4],
        text: 'Drug pricing concerns weigh on the {sector} sector',
    },
    {
        id: 42,
        scope: 'ticker',
        sectors: ['PHARMA'],
        sentimentRange: [5, 9],
        text: '{ticker} reports positive trial results for a promising treatment',
    },
    {
        id: 43,
        scope: 'ticker',
        sectors: ['PHARMA'],
        sentimentRange: [-9, -5],
        text: '{ticker} pauses a study after safety concerns are reported',
    },
    {
        id: 44,
        scope: 'ticker',
        sectors: ['PHARMA'],
        sentimentRange: [3, 6],
        text: '{ticker} receives a large order from hospital networks',
    },
    {
        id: 45,
        scope: 'ticker',
        sectors: ['PHARMA'],
        sentimentRange: [-6, -3],
        text: '{ticker} faces pressure from a lower-cost generic competitor',
    },
    {
        id: 46,
        scope: 'sector',
        sectors: ['TECH', 'FINANCE'],
        sentimentRange: [3, 6],
        text: 'Digital payment adoption accelerates, helping {sector} companies',
    },
    {
        id: 47,
        scope: 'sector',
        sectors: ['TECH', 'FINANCE'],
        sentimentRange: [-6, -3],
        text: 'Cybersecurity worries pressure {sector} companies',
    },
    {
        id: 48,
        scope: 'sector',
        sectors: ['RETAIL', 'MANUFACTURING'],
        sentimentRange: [3, 6],
        text: 'Freight costs fall, supporting {sector} margins',
    },
    {
        id: 49,
        scope: 'sector',
        sectors: ['RETAIL', 'MANUFACTURING'],
        sentimentRange: [-6, -3],
        text: 'Port congestion raises delivery costs for {sector} companies',
    },
    {
        id: 50,
        scope: 'sector',
        sectors: ['PHARMA', 'TECH'],
        sentimentRange: [3, 6],
        text: 'New health data tools boost growth hopes for {sector} companies',
    },
    {
        id: 51,
        scope: 'sector',
        sectors: ['PHARMA', 'TECH'],
        sentimentRange: [-6, -3],
        text: 'Stricter patient data rules add costs for {sector} companies',
    },
    {
        id: 52,
        scope: 'sector',
        sectors: ['FINANCE', 'RETAIL'],
        sentimentRange: [3, 6],
        text: 'Stronger consumer credit trends help {sector} companies',
    },
    {
        id: 53,
        scope: 'sector',
        sectors: ['FINANCE', 'RETAIL'],
        sentimentRange: [-6, -3],
        text: 'Household budget stress weighs on {sector} companies',
    },
    {
        id: 54,
        scope: 'sector',
        sectors: ['MANUFACTURING', 'TECH'],
        sentimentRange: [4, 7],
        text: 'Chip supply improves, helping {sector} production plans',
    },
    {
        id: 55,
        scope: 'sector',
        sectors: ['MANUFACTURING', 'TECH'],
        sentimentRange: [-7, -4],
        text: 'Chip shortages return and slow {sector} growth plans',
    },
    {
        id: 56,
        scope: 'sector',
        sectors: ['MANUFACTURING', 'PHARMA'],
        sentimentRange: [4, 7],
        text: 'Lower energy prices reduce operating costs for {sector} companies',
    },
    {
        id: 57,
        scope: 'sector',
        sectors: ['MANUFACTURING', 'PHARMA'],
        sentimentRange: [-7, -4],
        text: 'Higher energy prices raise operating costs for {sector} companies',
    },
    {
        id: 58,
        scope: 'global',
        sentimentRange: [2, 6],
        text: 'Global trade talks make progress and improve market confidence',
    },
    {
        id: 59,
        scope: 'global',
        sentimentRange: [-6, -2],
        text: 'Global trade talks break down and increase market uncertainty',
    },
    {
        id: 60,
        scope: 'global',
        sentimentRange: [3, 7],
        text: 'Inflation cools faster than expected, boosting investor confidence',
    },
    {
        id: 61,
        scope: 'global',
        sentimentRange: [-7, -3],
        text: 'Inflation rises faster than expected, hurting investor confidence',
    },
    {
        id: 62,
        scope: 'global',
        sentimentRange: [2, 5],
        text: 'Central banks signal a slower pace of rate increases',
    },
    {
        id: 63,
        scope: 'global',
        sentimentRange: [-5, -2],
        text: 'Central banks warn that interest rates may stay high for longer',
    },
    {
        id: 64,
        scope: 'global',
        sentimentRange: [3, 6],
        text: 'Global supply chains improve as shipping times fall',
    },
    {
        id: 65,
        scope: 'global',
        sentimentRange: [-6, -3],
        text: 'Global supply chains tighten as shipping times increase',
    },
    {
        id: 66,
        scope: 'global',
        sentimentRange: [2, 5],
        text: 'Consumer confidence improves across major economies',
    },
    {
        id: 67,
        scope: 'global',
        sentimentRange: [-5, -2],
        text: 'Consumer confidence weakens across major economies',
    },
    {
        id: 68,
        scope: 'global',
        sentimentRange: [4, 8],
        text: 'Major peace agreement reduces geopolitical risk for global markets',
    },
    {
        id: 69,
        scope: 'global',
        sentimentRange: [-8, -4],
        text: 'New geopolitical conflict raises risk for global markets',
    },
    {
        id: 70,
        scope: 'global',
        sentimentRange: [3, 6],
        text: 'Oil prices fall, easing costs for businesses and consumers',
    },
    {
        id: 71,
        scope: 'global',
        sentimentRange: [-6, -3],
        text: 'Oil prices jump, raising costs for businesses and consumers',
    },
    {
        id: 72,
        scope: 'global',
        sentimentRange: [2, 5],
        text: 'Job growth remains steady without adding inflation pressure',
    },
    {
        id: 73,
        scope: 'global',
        sentimentRange: [-5, -2],
        text: 'Job growth slows sharply and raises recession concerns',
    },
    {
        id: 74,
        scope: 'global',
        sentimentRange: [3, 6],
        text: 'Business investment plans rise across several industries',
    },
    {
        id: 75,
        scope: 'global',
        sentimentRange: [-6, -3],
        text: 'Business investment plans are delayed across several industries',
    },
];
